/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package radiosveglia;

import java.util.HashSet;
import java.util.Random;
import javax.swing.Timer;

/**
 *
 * @author bernicchi.davide
 */
public class SchermoSveglia extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SchermoSveglia.class.getName());

    Sveglia sv;
    Date data;
    
    /**
     * Creates new form SchermoSveglia
     */
    public SchermoSveglia() {
        initComponents();
        sv = new Sveglia();
        data = new Date("01", "01","2000");
        sv.set_data(data);
        this.buttom_disattiva.setVisible(false);
        this.buttom_snooze.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_impOra = new javax.swing.JButton();
        button_impSvegl = new javax.swing.JButton();
        button_impData = new javax.swing.JButton();
        button_cambiaStazione = new javax.swing.JButton();
        button_plus = new javax.swing.JButton();
        button_minus = new javax.swing.JButton();
        button_random = new javax.swing.JButton();
        lbl_volume = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tP_ora = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tP_svegl = new javax.swing.JTextPane();
        lbl_ora = new javax.swing.JLabel();
        lbl_svegl = new javax.swing.JLabel();
        lbl_data = new javax.swing.JLabel();
        lbl_staz = new javax.swing.JLabel();
        cB_staz = new javax.swing.JComboBox<>();
        lbl_schermo = new javax.swing.JLabel();
        button_avvio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tB_day = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tB_month = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        tB_year = new javax.swing.JTextPane();
        buttom_snooze = new javax.swing.JButton();
        buttom_disattiva = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        button_impOra.setFont(new java.awt.Font("Gentium Basic", 0, 18)); // NOI18N
        button_impOra.setText("imposta ora");
        button_impOra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_impOraActionPerformed(evt);
            }
        });

        button_impSvegl.setFont(new java.awt.Font("Gentium Basic", 0, 18)); // NOI18N
        button_impSvegl.setText("imposta sveglia");
        button_impSvegl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_impSveglActionPerformed(evt);
            }
        });

        button_impData.setFont(new java.awt.Font("Gentium Basic", 0, 18)); // NOI18N
        button_impData.setText("imposta data");
        button_impData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_impDataActionPerformed(evt);
            }
        });

        button_cambiaStazione.setFont(new java.awt.Font("Gentium Basic", 0, 18)); // NOI18N
        button_cambiaStazione.setText("cambia stazione");
        button_cambiaStazione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cambiaStazioneActionPerformed(evt);
            }
        });

        button_plus.setFont(new java.awt.Font("Gentium Basic", 0, 14)); // NOI18N
        button_plus.setText("+");
        button_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_plusActionPerformed(evt);
            }
        });

        button_minus.setFont(new java.awt.Font("Gentium Basic", 0, 14)); // NOI18N
        button_minus.setText("-");
        button_minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_minusActionPerformed(evt);
            }
        });

        button_random.setFont(new java.awt.Font("Gentium Basic", 0, 18)); // NOI18N
        button_random.setText("imposta randomicamente");
        button_random.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_randomActionPerformed(evt);
            }
        });

        lbl_volume.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        lbl_volume.setText("0");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(102, 15));

        tP_ora.setPreferredSize(new java.awt.Dimension(100, 30));
        jScrollPane1.setViewportView(tP_ora);

        tP_svegl.setPreferredSize(new java.awt.Dimension(100, 20));
        jScrollPane2.setViewportView(tP_svegl);

        lbl_ora.setBackground(new java.awt.Color(255, 255, 255));
        lbl_ora.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        lbl_ora.setText("00:00");
        lbl_ora.setToolTipText("");

        lbl_svegl.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        lbl_svegl.setText("00:00");

        lbl_data.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        lbl_data.setText("01/01/2000");

        lbl_staz.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        lbl_staz.setText("radio");

        cB_staz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Immagines Dragons [Ficarras Way]", "Artic Monkeys [Ficarras Way]", "Averil lavine  [Ficarras Way]", "E621", "Kanye West", "MF DOOM", "Shin Godzilla -Host", "Eyes wide shut -Host" }));
        cB_staz.setToolTipText("");
        cB_staz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cB_stazActionPerformed(evt);
            }
        });

        lbl_schermo.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        lbl_schermo.setText("00:00");

        button_avvio.setFont(new java.awt.Font("Gentium Basic", 0, 36)); // NOI18N
        button_avvio.setText("avvia");
        button_avvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_avvioActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1.setText("bisogna impostare l'ora e la sveglia per forza, in orario militare , il giorno non deve essere per forza inizializzato");

        jScrollPane3.setViewportView(tB_day);

        jScrollPane4.setViewportView(tB_month);

        jScrollPane5.setViewportView(tB_year);

        buttom_snooze.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 36)); // NOI18N
        buttom_snooze.setText("snooze");
        buttom_snooze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttom_snoozeActionPerformed(evt);
            }
        });

        buttom_disattiva.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 36)); // NOI18N
        buttom_disattiva.setText("disattiva");
        buttom_disattiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttom_disattivaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel2.setText(", nel momento in  cui la sveglia suona, la lbl radio prendera il node dell cantante/band selezzionata");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_avvio, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(button_cambiaStazione, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(button_impData)
                                .addComponent(button_impSvegl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(button_impOra))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cB_staz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(lbl_staz))
                                    .addComponent(lbl_schermo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_ora)
                                    .addComponent(lbl_svegl)
                                    .addComponent(lbl_data))
                                .addGap(120, 120, 120))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttom_snooze, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttom_disattiva, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(button_minus)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl_volume, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(button_plus))
                                    .addComponent(button_random)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttom_snooze, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttom_disattiva, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_avvio)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                            .addComponent(button_impOra, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_schermo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_ora)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lbl_svegl))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(button_impSvegl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_data)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_impData, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_cambiaStazione)
                    .addComponent(cB_staz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_staz))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_minus)
                    .addComponent(button_plus)
                    .addComponent(lbl_volume))
                .addGap(5, 5, 5)
                .addComponent(button_random)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_plusActionPerformed
        // TODO add your handling code here:
        sv.set_volume(Integer.parseInt(lbl_volume.getText()));
        int number = Integer.parseInt(sv.get_volume());        
        if (number < 10){
            lbl_volume.setText(null);
            lbl_volume.setText(""+ (number+1));
        }
        else{
            lbl_volume.setText("10");            
        }
    }//GEN-LAST:event_button_plusActionPerformed

    private void button_minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_minusActionPerformed
        // TODO add your handling code here:     
        sv.set_volume(Integer.parseInt(lbl_volume.getText()));
        int number = Integer.parseInt(sv.get_volume());
        if (number > 0){
            lbl_volume.setText(null);
            lbl_volume.setText(""+ (number-1));
        }
        else {
            lbl_volume.setText("0");            
        }
    }//GEN-LAST:event_button_minusActionPerformed

    private void button_impOraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_impOraActionPerformed
        // TODO add your handling code here:
        String t = tP_ora.getText();
        if (t != ""){
            if (t.length() == 4){
                int metà = t.length() / 2;
                sv.set_ora(Integer.parseInt(t.substring(0, metà)), Integer.parseInt(t.substring(metà)));
                lbl_ora.setText(sv.get_orario());
                lbl_schermo.setText(sv.get_orario());
                tP_ora.setText("");
            }
        }
        else {
            sv.set_ora(0, 0);
            lbl_ora.setText("00:00");
            lbl_schermo.setText("00:00");
        }
    }//GEN-LAST:event_button_impOraActionPerformed

    private void button_impSveglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_impSveglActionPerformed
        // TODO add your handling code here:
        String t = tP_svegl.getText();
        if (t != ""){
            if (t.length() == 4){
                int metà = t.length() / 2;
                sv.set_oraSveglia(Integer.parseInt(t.substring(0, metà)), Integer.parseInt(t.substring(metà)));
                lbl_svegl.setText(sv.get_orarioS());
                tP_svegl.setText("");
            }

        }
        else {
            sv.set_oraSveglia(0, 0);
            lbl_svegl.setText("00:00");
        }
    }//GEN-LAST:event_button_impSveglActionPerformed

    private void button_impDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_impDataActionPerformed
        // TODO add your handling code here:
        if (tB_day.getText()!= "" && tB_month.getText() != "" && tB_year.getText() != ""  ){
            data.set_date(tB_day.getText(),tB_month.getText(),tB_year.getText());
            lbl_data.setText(data.get_data());
            tB_month.setText("");
            tB_day.setText("");
            tB_year.setText("");
        }
        else{
            lbl_data.setText("01/01/01");
            tB_month.setText("");
            tB_day.setText("");
            tB_year.setText("");
        }
    }//GEN-LAST:event_button_impDataActionPerformed

    private void button_cambiaStazioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cambiaStazioneActionPerformed

        lbl_staz.setText(""+cB_staz.getSelectedItem());
    }//GEN-LAST:event_button_cambiaStazioneActionPerformed

    private void cB_stazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cB_stazActionPerformed
        cB_staz.addItem("radio subasio");
        cB_staz.addItem("Herz621");
        cB_staz.addItem("Kanye West");
        cB_staz.addItem("MF DOOM");
        cB_staz.addItem("inferno");
    }//GEN-LAST:event_cB_stazActionPerformed

    private void button_randomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_randomActionPerformed

        Random r = new Random();
        this.lbl_volume.setText("" + r.nextInt(11));
        
        sv.set_oraSveglia(r.nextInt(25), r.nextInt(61));
        this.lbl_svegl.setText(sv.get_oraS() + ":" + sv.get_minS()); 
        
        sv.set_ora(r.nextInt(25-sv.get_oraS()), r.nextInt(61-sv.get_minS()));
        this.lbl_ora.setText(sv.get_ora() + ":" + sv.get_min());
        this.lbl_schermo.setText(sv.get_orario());
        
        this.lbl_data.setText(r.nextInt(31) + "/" + r.nextInt(13) +"/"+r.nextInt(1000, 3000));
        this.tB_day.setText("");
        this.tB_month.setText("");
        this.tP_ora.setText("");
        this.tP_svegl.setText("");
        this.tB_year.setText("");
    }//GEN-LAST:event_button_randomActionPerformed

    private void button_avvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_avvioActionPerformed

        Timer t = new Timer(1000, e-> {
            sv.aumentoMin();
            this.lbl_schermo.setText(sv.get_orario());
            if (sv.get_orario().equals(sv.get_orarioS())){
                ((Timer) e.getSource()).stop();  
                this.buttom_disattiva.setVisible(true);
                this.buttom_snooze.setVisible(true);
                lbl_staz.setText("" + cB_staz.getSelectedItem());
            }
            lbl_data.setText(data.get_data());
        });
        t.start();

//this.lblblbl.setText("" + sv.get_timerMS());
        
    }//GEN-LAST:event_button_avvioActionPerformed

    private void buttom_snoozeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttom_snoozeActionPerformed
        // TODO add your handling code here:
        this.buttom_disattiva.setVisible(false);
        this.buttom_snooze.setVisible(false);
        sv.set_oraSveglia(sv.get_oraS(), sv.get_minS() + 5);
        Timer t = new Timer(1000, e->{
            sv.aumentoMin();
            this.lbl_schermo.setText(sv.get_orario()); 
            if (sv.get_orario().equals(sv.get_orarioS())){
                this.buttom_disattiva.setVisible(true);
                this.buttom_snooze.setVisible(true);
                ((Timer) e.getSource()).stop();  
            }
            
        });
        t.start();
    }//GEN-LAST:event_buttom_snoozeActionPerformed

    private void buttom_disattivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttom_disattivaActionPerformed
        // TODO add your handling code here
        this.buttom_disattiva.setVisible(false);
        this.buttom_snooze.setVisible(false);
        this.lbl_volume.setText("0");
        
        this.lbl_ora.setText("00:00"); 
        
        
        this.lbl_svegl.setText("00:00");
        this.lbl_schermo.setText("00:00");
        
        this.lbl_data.setText("01/01/2000");
    }//GEN-LAST:event_buttom_disattivaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SchermoSveglia().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttom_disattiva;
    private javax.swing.JButton buttom_snooze;
    private javax.swing.JButton button_avvio;
    private javax.swing.JButton button_cambiaStazione;
    private javax.swing.JButton button_impData;
    private javax.swing.JButton button_impOra;
    private javax.swing.JButton button_impSvegl;
    private javax.swing.JButton button_minus;
    private javax.swing.JButton button_plus;
    private javax.swing.JButton button_random;
    private javax.swing.JComboBox<String> cB_staz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbl_data;
    private javax.swing.JLabel lbl_ora;
    private javax.swing.JLabel lbl_schermo;
    private javax.swing.JLabel lbl_staz;
    private javax.swing.JLabel lbl_svegl;
    private javax.swing.JLabel lbl_volume;
    private javax.swing.JTextPane tB_day;
    private javax.swing.JTextPane tB_month;
    private javax.swing.JTextPane tB_year;
    private javax.swing.JTextPane tP_ora;
    private javax.swing.JTextPane tP_svegl;
    // End of variables declaration//GEN-END:variables
}
